name: CI for PHP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer

    - name: Install MySQL
      run: |
        choco install mysql --version=5.7 -y
        mysql --version

    - name: Configure MySQL
      run: |
        mysql -u root -e "CREATE DATABASE testdb;"
        mysql -u root -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'userpassword';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON testdb.* TO 'user'@'localhost';"
        mysql -u root -e "FLUSH PRIVILEGES;"

    - name: Install Dependencies
      run: composer install

    - name: Run Tests
      env:
        DB_HOST: localhost
        DB_DATABASE: testdb
        DB_USERNAME: user
        DB_PASSWORD: userpassword
      run: vendor/bin/phpunit
